[package]
name = "plonkbyhand"
version = "0.1.0"

[dependencies]
halo2 =  {git = "https://github.com/zcash/halo2", branch = "main", features = ["dev-graph", "gadget-traces", "sanity-checks"], optional = true}
